# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hub31app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hub31app
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'

  

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'hub31appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hub31app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hub31app-tvOS

  target 'hub31app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
