# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hub31app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hub31app
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'



  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'hub31appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hub31app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hub31app-tvOS

  target 'hub31app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
